# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa37ff32d8b0eef747c082e7e13bb19a631339c3ccffae198f6eb3ad1ed6176ce9960847c1f01ed70a1f2e36621ada49b78fe0b39b08eca2356be13d2bb25e0c

test:
  secret_key_base: 61caff3321c6282ed76ae33775283e817d1381786b76e9441c26807b5e53373b88620c7a49a93e733af7a05eff595ae41581f924a59fbd78b43cb8264e415071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
